// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
//
// Pegged asModule — same split as libwasm webidl-grammar/generator.
// Writes source/svelte_d/grammar/sveltekit.d (do not mixin the PEG).
module generator;

import std.file : readText, mkdirRecurse;
import std.path : buildNormalizedPath, dirName;
import std.stdio : writeln;
import pegged.grammar;

void main()
{
	auto here = dirName(__FILE_FULL_PATH__);
	auto pegPath = buildNormalizedPath(here, "..", "sveltekit.peg");
	auto outDir = buildNormalizedPath(here, "..", "..", "source", "svelte_d", "grammar");
	auto peg = readText(pegPath);
	mkdirRecurse(outDir);
	auto outFile = buildNormalizedPath(outDir, "sveltekit");
	asModule!(Memoization.no)("svelte_d.grammar.sveltekit", outFile, peg,
		"// Generated by grammar/generator. Source of truth: grammar/sveltekit.peg.\n"
			~ "// mixin(grammar) overflows LDC 1.42 + Pegged 0.4.9; this module is asModule.");
	writeln("wrote ", outFile, ".d");
}
