// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
import { describe, expect, test } from 'bun:test'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  compileWorkspace,
  dropWorkspace,
  workspaceDir,
  templateDir,
  extractDomUdas,
  domUdas,
} from 'svelte-d'
import { EACH_IF_CMP_CASES } from './if-cmp-cases.ts'
import { EACH_IF_BOOL_CASES } from './if-bool-cases.ts'
import { HOST_IF_CASES } from './if-host-cases.ts'
import { EACH_ELSE_CASES } from './each-else-cases.ts'
import { AWAIT_CASES } from './await-cases.ts'
import { BIND_CASES } from './bind-cases.ts'
import { DIRECTIVE_CASES } from './directive-cases.ts'
import { SPECIAL_CASES } from './special-cases.ts'
import { BOUNDARY_CASES } from './boundary-cases.ts'

describe('NodeDef / UDA graph from interactive Svelte', () => {
  test('engine fixtures exist', () => {
    const tpl = templateDir()
    expect(existsSync(join(tpl, 'src-svelte', 'lib', 'ClickField.svelte'))).toBe(true)
    expect(existsSync(join(tpl, 'src-svelte', 'lib', 'ListEvents.svelte'))).toBe(true)
  })

  test('button+field prints NodeDef, @callback, @connect, @prop, this.update', () => {
    const ws = workspaceDir()
    expect(dropWorkspace({ force: true }).status).toBe(0)
    const c = compileWorkspace(ws)
    expect(c.status).toBe(0)
    expect(c.stdout).toMatch(/dom=/)

    const p = join(ws, 'src-d', 'lib', 'ClickField.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ClickField')
    expect(src).toContain('struct ClickField')
    expect(src).toContain('string msg')
    expect(src).toContain('@prop!"textContent" string msg')
    expect(src).toContain('@trusted:')
    expect(src).toContain('struct GoButton')
    expect(src).toContain('@child GoButton goButton')
    expect(src).toContain('@connect!"goButton.click"')
    expect(src).toContain('go();')
    expect(src).toContain('void onMount()')
    expect(src).toContain('void onUnmount()')
    expect(src).toContain('@inject!"m_pool"')
    expect(src).toContain('ScopedPool(m_pool)')
    expect(src).toContain('struct MsgSpan')
    expect(src).toContain('mixin NodeDef!"div"')
    expect(src).toContain('mixin NodeDef!"button"')
    expect(src).toContain('mixin NodeDef!"span"')
    expect(src).toContain('@callback!"click"')
    expect(src).toContain('@prop')
    expect(src).toContain('@child')
    expect(src).toContain('msgSpan.update.msg')
    expect(src).toContain('compile!()')
    expect(src).toContain('NamedNode')
    expect(src).toContain('TagHtmlElementMap')
    const udas = extractDomUdas(src)
    expect(udas).toContain('NodeDef')
    expect(udas).toContain('callback')
    expect(udas).toContain('connect')
    expect(udas).toContain('prop')
    expect(domUdas).toContain('NodeDef')
  })

  test('each-list prints UnorderedList, inject!, list @connect with size_t', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ListEvents.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ListEvents')
    expect(src).toContain('struct ListEvents')
    expect(src).toContain('struct Item')
    expect(src).toContain('ItemsList items')
    expect(src).toContain('HTMLArray!Item')
    expect(src).toContain('@inject!"host"')
    expect(src).toContain('@connect!("items.items","picked")')
    expect(src).toContain('size_t idx')
    expect(src).toContain('mixin Slot!("picked", string)')
    expect(src).toContain('mixin NodeDef!"li"')
    expect(src).toContain('assignEventListeners')
    expect(src).toContain('HTMLArray')
    expect(src).toContain('ArrayItemEvents')
    expect(src).toContain('void construct() @trusted')
    expect(src).toContain('items.put(new')
    expect(src).toContain('@prop!"textContent" string last')
    const udas = extractDomUdas(src)
    expect(udas).toContain('inject')
    expect(udas).toContain('HTMLArray')
    expect(udas).toContain('Slot')

    const ir = join(ws, '.svelte-d', 'ir', 'dom-src-d_lib_ListEvents.d.json')
    expect(existsSync(ir)).toBe(true)
    const node = JSON.parse(readFileSync(ir, 'utf8'))
    expect(node.ir).toBe('libwasm-dom')
    expect(node.kind).toBe('Template')

    const man = JSON.parse(readFileSync(join(ws, '.svelte-d', 'manifest.json'), 'utf8'))
    expect(man.dom).toBeGreaterThan(0)
  })

  test('{#if} prints @visible and remount/unmount, not a second struct type', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'IfToggle.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.IfToggle')
    expect(src).toContain('struct IfToggle')
    expect(src).toContain('@visible!"openP"')
    expect(src).toContain('bool open')
    expect(src).toContain('struct OpenP')
    expect(src).toContain('@child OpenP openP')
    expect(src).toContain('void toggle()')
    expect(src).toContain('setVisible!"openP"')
    expect(src).toContain('not_open = !(')
    expect(src).toContain('ScopedPool(m_pool)')
    expect(src).toContain('mixin NodeDef!"p"')
    expect(src).toContain('text = "Visible"')
    expect(src).toContain('text = "Hidden"')
    expect(src).toContain('else_open')
    expect(src).toContain('setVisible!"else_')
    expect(src).not.toContain('mixin Spa!IfToggle')
    const udas = extractDomUdas(src)
    expect(udas).toContain('visible')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child IfToggle ifToggle')
    expect(app).toContain('import lib.IfToggle')
  })

  test('printed lib structs hang as @child on Spa!App with construct/onMount', () => {
    const ws = workspaceDir()
    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('mixin Spa!App')
    expect(app).toContain('import lib.ClickField')
    expect(app).toContain('@child ClickField clickField')
    expect(app).toContain('import lib.ListEvents')
    expect(app).toContain('@child ListEvents listEvents')
    expect(app).toContain('void construct()')
    expect(app).toContain('ManagedPool m_pool')
    expect(app).toContain('// svelte-d:begin-children')
    expect(app).not.toContain('mixin Spa!ClickField')
    expect(app).toContain('import lib.Dock')
    expect(app).not.toContain('import dock;')
    expect(app).toContain('import lib.NavBar')
    expect(app).not.toContain('import navbar;')
    expect(app).toContain('@child NavBar navbar')
    expect(app).toContain('kitRoutes.rootPage.show(name)')
    expect(app).not.toContain('@child Main content')
    expect((app.match(/@child Dock dock/g) || []).length).toBe(1)
    expect((app.match(/@child NavBar navbar/g) || []).length).toBe(1)

    const dock = readFileSync(join(ws, 'src-d', 'lib', 'Dock.d'), 'utf8')
    expect(dock).toMatch(/parse=pegged/)
    expect(dock).toContain('mixin Slot!("navigate", string)')
    expect(dock).not.toContain('mixin Slot!"navigate"')
    const bar = readFileSync(join(ws, 'src-d', 'lib', 'NavBar.d'), 'utf8')
    expect(bar).toContain('module lib.NavBar')
    expect(bar).toContain('struct NavBar')
    expect(bar).toContain('import pglite')
    expect(bar).toContain('@style!"navbar"')
    expect(bar).toContain('throw new Exception("svelte-engine-eh")')
    expect(bar).toContain('PgLite().query')
    expect(bar).toContain('mixin NodeDef!"div"')
    expect(bar).toContain('void toggle()')
    expect(bar).toContain('bool open')
    expect(bar).toContain('@style!"burger-menu"')
    expect(bar).toContain('UnorderedList!Link links')
    expect(bar).toContain('@style!"burger"')
    const home = readFileSync(join(ws, 'src-d', 'routes', 'page.d'), 'utf8')
    expect(home).toContain('import jshost : formatNow')
    expect(home).toContain('formatNow("HH:mm")')

    const click = readFileSync(join(ws, 'src-d', 'lib', 'ClickField.d'), 'utf8')
    const goIdx = click.indexOf('void go()')
    expect(goIdx).toBeGreaterThan(-1)
    const goSlice = click.slice(goIdx, goIdx + 120)
    expect(goSlice).toContain('ScopedPool(m_pool)')
    expect(click).not.toContain('= Go;')
    expect(click).toContain('text = "Go"')
  })

  test('official AST coverage: class:, style:, bind:checked, {@html}, Component, each else', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'LangCoverage.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.LangCoverage')
    expect(src).toContain('@style!"on"')
    expect(src).toContain('bool on')
    expect(src).toContain('@prop!"checked"')
    expect(src).toContain('@prop!"innerHTML"')
    expect(src).toContain('@attr!"id"')
    expect(src).toContain('@prop!"style"')
    expect(src).toContain('toneP.tone = tone')
    expect(src).toContain('import lib.ClickField')
    expect(src).toContain('@child ClickField clickField')
    expect(src).toContain('@child ExtrasList extras')
    expect(src).not.toContain('UnorderedList!Extra extras')
    expect(src).toContain('extras.put')
    expect(src).not.toMatch(/section\d+\.extras\.put/)
    expect(src).toContain('extras_empty')
    expect(src).toContain('extras_empty = false')
    expect(src).toContain('text = "Empty"')
    expect(src).toContain('extras.shrinkTo(0)')
    expect(src).toContain('setVisible!"empty_extrasP"(extras, true)')
    {
      const i = src.indexOf('struct ExtrasList')
      expect(i).toBeGreaterThan(-1)
      const j = src.indexOf('struct EmptyExtrasP', i)
      expect(j).toBeGreaterThan(i)
      const lst = src.slice(i, j)
      expect(lst).toContain('@child EmptyExtrasP')
      expect(lst).toContain('mixin NodeDef!"ul"')
      expect(src.slice(0, i)).not.toContain('@child EmptyExtrasP')
    }
    expect(src).toContain('UnorderedList!V voids')
    expect(src).toContain('voids_empty = true')
    expect(src).toContain('text = "None"')
    expect(src).not.toContain('voids.put')
    expect(src).not.toMatch(/string\[\]\s+voids/)
    expect(src).toContain('mixin NodeDef!"section"')
    expect(src).toContain('text = "On"')
    expect(src).toContain('text = "Off"')
    expect(src).toMatch(/section\d+\.update\.on = on/)
    expect(src).toMatch(/section\d+\.update\.not_on/)
    expect(src).toMatch(/section\d+\.not_on = !on/)
    {
      const i = src.indexOf('struct Section')
      const j = src.indexOf('struct OnP')
      expect(i).toBeGreaterThan(-1)
      expect(j).toBeGreaterThan(i)
      const sec = src.slice(i, j)
      expect(sec).toContain('@child OnP')
      expect(sec).toContain('@visible!"onP"')
      expect(sec).toContain('@child ElseOnP')
      expect(sec).not.toContain('struct OnP')
    }
    expect(src).not.toContain('mixin NodeDef!"clickfield"')
    expect(src).not.toContain('mixin NodeDef!"ClickField"')

    const list = readFileSync(join(ws, 'src-d', 'lib', 'ListEvents.d'), 'utf8')
    expect(list).toContain('ItemsList items')
    expect(list).toContain('items_empty')
    expect(list).toContain('text = "Empty"')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child LangCoverage langCoverage')
  })

  test('combinatorial coverage: if+elseif+else, each+index+class, await, slot, component props', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'Combo.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.Combo')
    expect(src).toMatch(/parse=scan-/)
    expect(src).toContain('@visible!"showP"')
    expect(src).toContain('bool show')
    expect(src).toContain('bool other')
    expect(src).toContain('text = "Other"')
    expect(src).toContain('mixin Slot!"default_"')
    expect(src).toContain('text = "fallback"')
    expect(src).toContain('await_pending')
    expect(src).toContain('await_then')
    expect(src).toContain('await_catch')
    expect(src).toContain('await_pending = true')
    expect(src).toContain('await_then = false')
    expect(src).toContain('JsPromise!Any job')
    expect(src).toContain('await_then = true')
    expect(src).toContain('void wireAwait()')
    const appReady = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(appReady).toContain('combo.wireAwait()')
    expect(appReady).toContain('void ready()')
    expect(src).toContain('text = "Wait"')
    expect(src).toContain('text = "Done"')
    expect(src).toContain('text = "Err"')
    expect(src).toContain('UnorderedList!Item items')
    expect(src).toContain('@style!"on"')
    expect(src).toContain('@attr!"title"')
    expect(src).toContain('import lib.ClickField')
    expect(src).toContain('clickField.msg = "hi"')
    expect(src).toContain('@prop!"value"')
    expect(src).toContain('@attr!"id"')
    expect(src).toContain('id_ = tone')
    expect(src).not.toMatch(/struct Input\d+[\s\S]*string tone;[\s\S]*string tone;/)
    expect(src).toContain('rawHtml.raw = raw')
    expect(src).toContain('@attr!"name"')
    expect(src).toContain('@prop!"innerHTML"')
    expect(src).toContain('items_empty')
  })

  test('combinatorial coverage: snippet+render, bind:this/group, const/debug, key, svelte:window, runes', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboMore.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboMore')
    expect(src).toContain('struct ComboMore')
    expect(src).toContain('text = "Hi"')
    expect(src).toContain('@child GreetP greetP')
    expect(src).toContain('int doubled = 2')
    expect(src).toContain('console.log("pick")')
    expect(src).toContain('remount!"stampP"')
    expect(src).toContain('void remount_stamp()')
    expect(src).toContain('Handle box')
    expect(src).toContain('box = boxDiv.node.handle.handle')
    expect(src).toContain('@attr!"name"')
    expect(src).toContain('name_ = "pick"')
    expect(src).toContain('@prop!"checked"')
    expect(src).toContain('window()')
    expect(src).toContain('on_svelte_window_keydown')
    expect(src).toContain('ev.preventDefault()')
    expect(src).toContain('string stamp = "a"')
    expect(src).toContain('string stampLabel')
    expect(src).toContain('stampLabel = stamp')
    expect(src).toContain('stampP.stamp = stamp')
    expect(src).not.toContain('$state')
    expect(src).not.toContain('$derived')
    expect(src).not.toContain('$effect')
    expect(src).toContain('console.log(stamp)')
    expect(src).toContain('stampP.update.stamp')
    expect(src).toContain('stamp = "b"')
    expect(src).toContain('input3.checked = (pick == "a")')
    expect(src).toContain('@connect!"input3.change"')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboMore comboMore')
    expect(app).toContain('import lib.ComboMore')
  })

  test('combinatorial coverage: svelte:element/fragment/component, use:, transition, spread, attach, snippet site', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboNext.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboNext')
    expect(src).toContain('struct ComboNext')
    expect(src).toContain('mixin NodeDef!"section"')
    expect(src).toContain('@style!"box"')
    expect(src).toContain('@style!"fade"')
    expect(src).toContain('@style!"fly"')
    expect(src).toContain('@style!"flip"')
    expect(src).toContain('focus(')
    expect(src).toContain('.node.handle.handle')
    expect(src).toContain('// spread props')
    expect(src).toContain('applySpread(props)')
    expect(src).toContain('text = "Dyn"')
    expect(src).toContain('text = "Frag"')
    expect(src).toContain('import lib.ClickField')
    expect(src).toContain('@child ClickField clickField')
    expect(src).toContain('clickField.msg = "hi"')
    expect(src).toContain('text = "site"')
    expect(src).toContain('attachFn(this.node.handle.handle)')
    expect(src).toContain('text = "Move"')
    expect(src).toContain('text = "Safe"')
    expect(src).toContain('boundary_ok = true')
    expect(src).not.toContain('mixin NodeDef!"svelte:element"')
    expect(src).not.toContain('mixin NodeDef!"svelte:fragment"')
    expect(src).not.toContain('mixin NodeDef!"svelte:component"')
    expect(src).not.toContain('mixin NodeDef!"svelte:boundary"')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboNext comboNext')
    expect(app).toContain('import lib.ComboNext')
  })

  test('combinatorial coverage: each key, let:, {let}, svelte:head title, svelte:options, svelte:self', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboRest.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboRest')
    expect(src).toContain('struct ComboRest')
    expect(src).toContain('// svelte:options namespace=html')
    expect(src).toContain('// svelte:options runes=true')
    expect(src).toContain('document().title("Rest")')
    expect(src).toContain('int extra = 3')
    expect(src).toContain('UnorderedList!Row rows')
    expect(src).toContain('@attr!"data-key"')
    expect(src).toContain('data_key_ = "row"')
    expect(src).toContain('int i; // each index')
    expect(src).toContain('string item; // let:item')
    expect(src).toContain('text = "fallback"')
    expect(src).toContain('// svelte:self')
    expect(src).toContain('@child ComboRest* selfKid')
    expect(src).toContain('@child SelfDiv selfDiv')
    expect(src).toContain('text = "Self"')
    expect(src).not.toContain('mixin NodeDef!"title"')
    expect(src).not.toContain('mixin NodeDef!"svelte:self"')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboRest comboRest')
    expect(app).toContain('import lib.ComboRest')
  })

  test('combinatorial coverage: <style> addCss, style: concat+important, dynamic svelte:element, spread attr', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboCss.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboCss')
    expect(src).toContain('struct ComboCss')
    expect(src).toContain('addCss("')
    expect(src).toContain('.box')
    expect(src).toContain('@style!"box"')
    expect(src).toContain('@style!"on"')
    expect(src).toContain('@attr!"data-tag"')
    expect(src).toContain('applyTag(tag)')
    expect(src).toContain('void applyTag(string tag)')
    expect(src).toContain('.data_tag = tag')
    expect(src).toContain('document().createElement(tag)')
    expect(src).toContain('replaceChild')
    expect(src).toContain('// spread rest')
    expect(src).toContain('@attr!"data-spread"')
    expect(src).toContain('applySpread(rest)')
    expect(src).toContain('void applySpread(string bag)')
    expect(src).toContain('node.setAttribute(key, bag[v0 .. i])')
    expect(src).toContain('Handle extra')
    expect(src).toContain('applySpread(extra)')
    expect(src).toContain('void applySpread(Handle bag)')
    expect(src).toContain('applyObjectSpread(node.handle.handle, bag)')
    expect(src).toContain('@prop!"style"')
    expect(src).toContain('.update.style = "color:" ~ tone')
    expect(src).toContain('"background:" ~ tone ~ " !important"')
    expect(src).toContain('text = "Paint"')
    expect(src).toMatch(/struct Div0[\s\S]*@child P1/)
    {
      const d0 = src.slice(src.indexOf('struct Div0'), src.indexOf('struct P1'))
      expect(d0).toContain('@child P1')
      expect(d0).not.toContain('struct P1')
    }
    expect(src).not.toContain('mixin NodeDef!"style"')
    expect(src).not.toContain('mixin NodeDef!"svelte:element"')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboCss comboCss')
    expect(app).toContain('import lib.ComboCss')
  })

  test('combinatorial coverage: textarea/select, bind:innerHTML/open, boolean disabled, on:once+multi', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboForm.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboForm')
    expect(src).toContain('struct ComboForm')
    expect(src).toContain('mixin NodeDef!"textarea"')
    expect(src).toContain('mixin NodeDef!"select"')
    expect(src).toContain('mixin NodeDef!"option"')
    expect(src).toContain('mixin NodeDef!"details"')
    expect(src).toContain('@prop!"value"')
    expect(src).toContain('textarea0.note = note')
    expect(src).toContain('@connect!"textarea0.input"')
    expect(src).toContain('note = textarea0.note')
    expect(src).toMatch(/struct Select\d+[\s\S]*@child Option/)
    {
      const i = src.indexOf('struct Select1')
      const j = src.indexOf('struct Option2')
      expect(i).toBeGreaterThan(-1)
      expect(j).toBeGreaterThan(i)
      const sel = src.slice(i, j)
      expect(sel).toContain('@child Option2')
      expect(sel).not.toContain('struct Option2')
    }
    expect(src).toMatch(/struct Details\d+[\s\S]*@child Summary/)
    {
      const i = src.indexOf('struct Details5')
      const j = src.indexOf('struct Summary6')
      expect(i).toBeGreaterThan(-1)
      expect(j).toBeGreaterThan(i)
      const det = src.slice(i, j)
      expect(det).toContain('@child Summary6')
      expect(det).not.toContain('struct Summary6')
    }
    expect(src).toContain('@prop!"innerHTML"')
    expect(src).toContain('div4.html = html')
    expect(src).toContain('@prop!"open"')
    expect(src).toContain('details5.open = open')
    expect(src).toContain('@attr!"disabled" bool disabled_ = true')
    expect(src).toContain('@style!"on" bool on')
    expect(src).toContain('mixin Slot!"click"')
    expect(src).toContain('mixin Slot!"keydown"')
    expect(src).toContain('_once_click')
    expect(src).toContain('save();')
    expect(src).toContain('tap();')
    expect(src).toContain('@connect!"saveButton.click"')
    expect(src).toContain('@connect!"saveButton.keydown"')
    expect(src).toContain('text = "A"')
    expect(src).toContain('text = "More"')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboForm comboForm')
    expect(app).toContain('import lib.ComboForm')
  })

  test('combinatorial coverage: svg/video/aria, bind:paused+muted, on:self|trusted, bool mustache, boundary failed', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboMedia.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboMedia')
    expect(src).toContain('struct ComboMedia')
    expect(src).toContain('mixin NodeDef!"svg"')
    expect(src).toContain('mixin NodeDef!"circle"')
    expect(src).toContain('mixin NodeDef!"video"')
    expect(src).toContain('mixin NodeDef!"a"')
    expect(src).toContain('mixin NodeDef!"img"')
    expect(src).toContain('@prop!"paused"')
    expect(src).toContain('@prop!"muted"')
    expect(src).toContain('@attr!"aria-label"')
    expect(src).toContain('@attr!"href"')
    expect(src).toContain('@attr!"disabled" bool disabled_')
    expect(src).toContain('hitButton.disabled_ = off')
    expect(src).toContain('ev.isTrusted()')
    expect(src).toContain('// on:self')
    expect(src).toContain('text = "Ok"')
    expect(src).toContain('boundary_ok = true')
    expect(src).toContain('boundary_failed = false')
    expect(src).toContain('void failBoundary(string msg)')
    expect(src).toContain('void throwBoundary(string msg)')
    expect(src).toContain('throw new Exception(msg)')
    expect(src).toContain('catch (Exception e)')
    expect(src).toContain('void resetBoundary()')
    expect(src).toContain('string boundary_error')
    expect(src).toContain('@style!"fail-msg"')
    expect(src).toContain('resetBoundary();')
    expect(src).toContain('oops(msg)')
    expect(src).toContain('throwBoundary("boom")')
    expect(src).toContain('setVisible!"errorP"')
    expect(src).toContain('text = "Go"')
    expect(src).toContain('@attr!"cx"')
    expect(src).toContain('@attr!"viewBox"')
    expect(src).toContain('hit();')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboMedia comboMedia')
    expect(app).toContain('import lib.ComboMedia')
  })

  test('combinatorial coverage: {#if !cond}, math/dialog/audio volume, custom element, svelte:document/body', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboWide.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboWide')
    expect(src).toContain('struct ComboWide')
    expect(src).toContain('bool not_off')
    expect(src).toContain('@visible!"offP"')
    expect(src).toContain('!off')
    expect(src).toContain('mixin NodeDef!"math"')
    expect(src).toContain('mixin NodeDef!"mi"')
    expect(src).toContain('mixin NodeDef!"dialog"')
    expect(src).toContain('mixin NodeDef!"audio"')
    expect(src).toContain('mixin NodeDef!"progress"')
    expect(src).toContain('mixin NodeDef!"canvas"')
    expect(src).toContain('mixin NodeDef!"iframe"')
    expect(src).toContain('mixin NodeDef!"my-widget"')
    expect(src).toContain('@prop!"open"')
    expect(src).toContain('@prop!"paused"')
    expect(src).toMatch(/div\d+\.update\.not_off/)
    expect(src).toMatch(/void onMount[\s\S]*setVisible!"offP"\(div\d+/)
    expect(src).not.toMatch(/div\d+\.off = off/)
    {
      const i = src.indexOf('struct Div0')
      const j = src.indexOf('struct FlipButton')
      expect(i).toBeGreaterThan(-1)
      expect(j).toBeGreaterThan(i)
      const div = src.slice(i, j)
      expect(div).toContain('@style!"combo-wide"')
      expect(div).toMatch(/@style!"combo-wide"\s*mixin NodeDef!"div"/)
      expect(div).not.toMatch(/@style!"combo-wide"\s*@child FlipButton/)
    }
    expect(src).toMatch(/audio\d+\.paused = paused/)
    expect(src).toContain('@prop!"volume" double vol')
    expect(src).toContain('@prop!"value" double wide')
    expect(src).toContain('on_svelte_document_visibilitychange')
    expect(src).toContain('on_svelte_body_mouseenter')
    expect(src).toContain('document()')
    expect(src).toContain('onVis()')
    expect(src).toContain('onEnter()')
    expect(src).toContain('text = "Shown"')
    expect(src).toContain('text = "Dlg"')
    expect(src).toContain('@attr!"data-k"')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboWide comboWide')
    expect(app).toContain('import lib.ComboWide')
  })

  test('combinatorial coverage: {#if a && b}, await {v}, render args, each {name}, table/form, clientWidth', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboExpr.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboExpr')
    expect(src).toContain('struct ComboExpr')
    expect(src).toContain('bool ready_and_ok')
    expect(src).toContain('ready_and_ok = ready && ok')
    expect(src).toContain('setVisible!"')
    expect(src).toContain('ready && ok')
    expect(src).toContain('text = "Both"')
    expect(src).toContain('@prop!"textContent" string v')
    expect(src).toContain('await_then')
    expect(src).toContain('nameSpan.name = who')
    expect(src).toContain('UnorderedList!Name rows')
    expect(src).toContain('@prop!"textContent" string name')
    expect(src).toContain('mixin NodeDef!"form"')
    expect(src).toContain('mixin NodeDef!"label"')
    expect(src).toContain('mixin NodeDef!"table"')
    expect(src).toMatch(/struct Table\d+[\s\S]*@child Thead/)
    expect(src).toContain('mixin NodeDef!"thead"')
    expect(src).toContain('mixin NodeDef!"tbody"')
    expect(src).toContain('mixin NodeDef!"th"')
    expect(src).toContain('mixin NodeDef!"td"')
    expect(src).toContain('ev.preventDefault()')
    expect(src).toContain('send();')
    expect(src).toContain('@callback!"submit"')
    expect(src).toContain('@attr!"for"')
    expect(src).toContain('int wide; // bind:clientWidth')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboExpr comboExpr')
    expect(app).toContain('import lib.ComboExpr')
  })

  test('combinatorial coverage: {#if a || b}, named slot, window bind:scrollY, picture/fieldset/meter, :global', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboOr.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboOr')
    expect(src).toContain('struct ComboOr')
    expect(src).toContain('bool left_or_right')
    expect(src).toContain('left_or_right = left || right')
    expect(src).toContain('text = "Either"')
    expect(src).toContain('@prop!"textContent" string v')
    expect(src).toContain('@prop!"textContent" string e')
    expect(src).toContain('await_catch')
    expect(src).toContain('mixin Slot!"aside"')
    expect(src).toContain('text = "Side"')
    expect(src).toContain('mixin NodeDef!"picture"')
    expect(src).toContain('mixin NodeDef!"source"')
    expect(src).toContain('mixin NodeDef!"fieldset"')
    expect(src).toContain('mixin NodeDef!"legend"')
    expect(src).toContain('mixin NodeDef!"meter"')
    expect(src).toContain('mixin NodeDef!"time"')
    expect(src).toContain('mixin NodeDef!"optgroup"')
    expect(src).toContain('@attr!"datetime"')
    expect(src).toContain('window().scrollY()')
    expect(src).toContain('sy = window().scrollY()')
    expect(src).toContain('on_svelte_window_resize')
    expect(src).toContain('boom()')
    expect(src).toContain('addCss("')
    expect(src).toContain('@style!"wide"')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboOr comboOr')
    expect(app).toContain('import lib.ComboOr')
  })

  test('combinatorial coverage: {#if n > 0}, bind:files, ruby/datalist/template/track, style:--var, drag', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboMisc.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboMisc')
    expect(src).toContain('struct ComboMisc')
    expect(src).toContain('bool n___0')
    expect(src).toContain('n___0 = n > 0')
    expect(src).toContain('setVisible!"')
    expect(src).toContain('n > 0')
    expect(src).toContain('text = "Pos"')
    expect(src).toContain('@prop!"files" Handle')
    expect(src).toContain('mixin NodeDef!"datalist"')
    expect(src).toContain('mixin NodeDef!"output"')
    expect(src).toContain('mixin NodeDef!"ruby"')
    expect(src).toContain('mixin NodeDef!"rt"')
    expect(src).toContain('mixin NodeDef!"map"')
    expect(src).toContain('mixin NodeDef!"area"')
    expect(src).toContain('mixin NodeDef!"track"')
    expect(src).toContain('mixin NodeDef!"caption"')
    expect(src).toContain('mixin NodeDef!"colgroup"')
    expect(src).toContain('mixin NodeDef!"tfoot"')
    expect(src).toContain('mixin NodeDef!"template"')
    expect(src).toContain('mixin NodeDef!"abbr"')
    expect(src).toContain('"--accent:" ~ tone')
    expect(src).toContain('DragEvent')
    expect(src).toContain('drag();')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboMisc comboMisc')
    expect(app).toContain('import lib.ComboMisc')
  })

  test('combinatorial coverage: (a && b), a == b, snippet pair args, component bind:this, semantic HTML', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboSem.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboSem')
    expect(src).toContain('struct ComboSem')
    expect(src).toContain('bool ready_and_ok')
    expect(src).toContain('ready_and_ok = ready && ok')
    expect(src).toContain('who == extra')
    expect(src).toContain('text = "Both"')
    expect(src).toContain('text = "Eq"')
    expect(src).toContain('.a = who')
    expect(src).toContain('.b = extra')
    expect(src).toContain('import lib.ClickField')
    expect(src).toContain('field = clickField.node.handle.handle')
    expect(src).toContain('Handle field')
    expect(src).toContain('@prop!"value" double amt')
    expect(src).toContain('mixin NodeDef!"article"')
    expect(src).toContain('mixin NodeDef!"header"')
    expect(src).toContain('mixin NodeDef!"h1"')
    expect(src).toContain('mixin NodeDef!"nav"')
    expect(src).toContain('mixin NodeDef!"main"')
    expect(src).toContain('mixin NodeDef!"section"')
    expect(src).toContain('mixin NodeDef!"figure"')
    expect(src).toContain('mixin NodeDef!"figcaption"')
    expect(src).toContain('mixin NodeDef!"pre"')
    expect(src).toContain('mixin NodeDef!"code"')
    expect(src).toContain('mixin NodeDef!"blockquote"')
    expect(src).toContain('mixin NodeDef!"dl"')
    expect(src).toContain('mixin NodeDef!"dt"')
    expect(src).toContain('mixin NodeDef!"dd"')
    expect(src).toContain('mixin NodeDef!"aside"')
    expect(src).toContain('mixin NodeDef!"footer"')
    expect(src).toContain('mixin NodeDef!"mark"')
    expect(src).toContain('mixin NodeDef!"kbd"')
    expect(src).toContain('mixin NodeDef!"noscript"')
    expect(src).toContain('mixin NodeDef!"hr"')
    expect(src).toContain('mixin NodeDef!"br"')
    expect(src).toContain('PointerEvent')
    expect(src).toContain('FocusEvent')
    expect(src).toContain('WheelEvent')
    expect(src).toContain('TouchEvent')
    expect(src).toContain('ping();')
    expect(src).toContain('ch();')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboSem comboSem')
    expect(app).toContain('import lib.ComboSem')
  })

  test('combinatorial coverage: on && !hide, each+if, [x,y], indeterminate, clipboard/scroll, more tags', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboNest.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboNest')
    expect(src).toContain('struct ComboNest')
    expect(src).toContain('bool on_and_hide')
    expect(src).toContain('on_and_hide = on && !hide')
    expect(src).toContain('text = "Show"')
    expect(src).toContain('UnorderedList!Item items')
    expect(src).toContain('void sync_items_on()')
    expect(src).toContain('sync_items_on()')
    expect(src).not.toContain('@visible!"items"')
    expect(src).not.toContain('setVisible!"items"')
    expect(src).toContain('void fill_rows()')
    expect(src).toContain('void wireEach()')
    expect(src).toContain('bool ok;')
    expect(src).not.toContain('bool row_ok')
    expect(src).not.toContain('void sync_rows_row_ok')
    for (const c of EACH_IF_BOOL_CASES) {
      expect(src).toContain('if (' + c.pred + ')')
      expect(src).toContain('void ' + c.sync + '()')
      expect(src).toContain('@style!"' + c.id + '-row"')
    }
    expect(src).toContain('mixin NodeDef!"li"')
    expect(src).toContain('UnorderedList!X pairs')
    expect(src).toContain('string y;')
    expect(src).toContain('@prop!"indeterminate"')
    expect(src).toContain('@attr!"reversed" bool reversed_ = true')
    expect(src).toContain('@attr!"type" string type_ = "email"')
    expect(src).toContain('mixin NodeDef!"object"')
    expect(src).toContain('mixin NodeDef!"embed"')
    expect(src).toContain('mixin NodeDef!"bdi"')
    expect(src).toContain('mixin NodeDef!"bdo"')
    expect(src).toContain('mixin NodeDef!"cite"')
    expect(src).toContain('mixin NodeDef!"dfn"')
    expect(src).toContain('mixin NodeDef!"address"')
    expect(src).toContain('mixin NodeDef!"wbr"')
    expect(src).toContain('ClipboardEvent')
    expect(src).toContain('CustomEvent')
    expect(src).toContain('copy();')
    expect(src).toContain('scroll();')

    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboNest comboNest')
    expect(app).toContain('import lib.ComboNest')
    expect(app).toContain('comboNest.wireEach()')
  })

  test('each-if cmp table: ops, host-first, !on, rhs != 0', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboIfCmp.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboIfCmp')
    expect(src).toContain('int n;')
    expect(src).toContain('void wireEach()')
    for (const c of EACH_IF_CMP_CASES) {
      expect(src).toContain('if (' + c.pred + ')')
      expect(src).toContain('void ' + c.sync + '()')
      if (c.seed.length)
        expect(src).toContain(c.seed)
      expect(src).toContain('@style!"ifcmp-' + c.id + '"')
    }
    expect(src).toContain('sync_lors_on()')
    expect(src).toContain('sync_gas_on()')
    expect(src).toContain('sync_hfs_on()')
    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboIfCmp comboIfCmp')
    expect(app).toContain('comboIfCmp.wireEach()')
  })

  test('host-if table: on, !on, &&, ||, n > 0, who == extra', () => {
    const ws = workspaceDir()
    const p = join(ws, 'src-d', 'lib', 'ComboIfHost.d')
    expect(existsSync(p)).toBe(true)
    const src = readFileSync(p, 'utf8')
    expect(src).toContain('module lib.ComboIfHost')
    for (const c of HOST_IF_CASES) {
      expect(src).toContain('@style!"ifhost-' + c.id + '"')
      expect(src).toContain(c.pred)
    }
    expect(src).toMatch(/void flip\(\)[\s\S]*setVisible/)
    expect(src).toContain('setVisible!"onSpan"(this, on)')
    expect(src).toContain('setVisible!"not_onSpan"(this, !(on))')
    expect(src).toContain('setVisible!"on_and_hideSpan"(this, on && !hide)')
    expect(src).toContain('setVisible!"flag_or_onSpan"(this, flag || on)')
    expect(src).toContain('@child NotOnSpan not_onSpan')
    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboIfHost comboIfHost')
  })

  test('each-else / await / bind tables: ComboCover + no-job dests', () => {
    const ws = workspaceDir()
    const cover = join(ws, 'src-d', 'lib', 'ComboCover.d')
    expect(existsSync(cover)).toBe(true)
    const src = readFileSync(cover, 'utf8')
    expect(src).toContain('module lib.ComboCover')
    for (const c of EACH_ELSE_CASES)
      for (const n of c.needles)
        expect(src).toContain(n)
    expect(src).toMatch(/void wipe\(\)[\s\S]*shrinkTo/)
    const byDest: Record<string, string> = { ComboCover: src }
    for (const dest of ['ComboExpr', 'ComboOr']) {
      const p = join(ws, 'src-d', 'lib', dest + '.d')
      expect(existsSync(p)).toBe(true)
      byDest[dest] = readFileSync(p, 'utf8')
    }
    for (const c of AWAIT_CASES) {
      const body = byDest[c.dest]
      expect(body).toBeTruthy()
      for (const n of c.needles)
        expect(body).toContain(n)
    }
    expect(src).toContain('void wireAwait()')
    expect(byDest.ComboExpr).not.toContain('void wireAwait()')
    for (const c of BIND_CASES)
      for (const n of c.needles)
        expect(src).toContain(n)
    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboCover comboCover')
    expect(app).toContain('comboCover.wireAwait()')
  })

  test('directive / special / boundary tables: ComboSurf + dests', () => {
    const ws = workspaceDir()
    const surf = join(ws, 'src-d', 'lib', 'ComboSurf.d')
    expect(existsSync(surf)).toBe(true)
    const src = readFileSync(surf, 'utf8')
    expect(src).toContain('module lib.ComboSurf')
    const byDest: Record<string, string> = { ComboSurf: src }
    for (const dest of ['ComboCss', 'ComboForm', 'ComboNext', 'ComboMedia', 'ComboMore', 'ComboWide']) {
      const p = join(ws, 'src-d', 'lib', dest + '.d')
      expect(existsSync(p)).toBe(true)
      byDest[dest] = readFileSync(p, 'utf8')
    }
    for (const c of DIRECTIVE_CASES) {
      const body = byDest[c.dest]
      expect(body).toBeTruthy()
      for (const n of c.needles)
        expect(body).toContain(n)
    }
    for (const c of SPECIAL_CASES) {
      const body = byDest[c.dest]
      expect(body).toBeTruthy()
      for (const n of c.needles)
        expect(body).toContain(n)
    }
    for (const c of BOUNDARY_CASES) {
      const body = byDest[c.dest]
      expect(body).toBeTruthy()
      for (const n of c.needles)
        expect(body).toContain(n)
    }
    const app = readFileSync(join(ws, 'src-d', 'app.d'), 'utf8')
    expect(app).toContain('@child ComboSurf comboSurf')
  })
})
