// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
//
// +page.server.* / +server.* → vibe.0 registerWebInterface under
// webserver/source/generated/. Free-function fixtures are wrapped in a class.
module svelte_d.print.host_attach;

import std.algorithm : canFind, startsWith;
import std.array : appender, join;
import std.file : exists, mkdirRecurse, readText, writeFile = write;
import std.path : baseName, buildPath, dirName, stripExtension;
import std.string : indexOf, replace, strip;
import svelte_d.fallthrough;
import svelte_d.parse.dlang;
import svelte_d.print.d_imports;
import svelte_d.workspace.files;

struct HostAttach
{
	string dest;
	string modName;
	string className;
	string kind;
	bool wrapped;
	bool errorHandler;
	bool ok = true;
	string detail;
	string[] authorImports;
	string[] rejectedImports;
}

/// Print one kit host file into webserver/source/generated/.
HostAttach attachHostFile(string ws, string srcSvelteRel, string srcPath)
{
	HostAttach a;
	auto ft = mapKitRel(srcSvelteRel);
	if (!ft.host.length)
		return a;
	a.dest = ft.host.replace(`\`, `/`);
	a.kind = ft.kind;
	a.modName = moduleFromHostDest(a.dest);
	a.className = classFromHostDest(a.dest);
	auto dest = buildPath(ws, a.dest);
	mkdirRecurse(dirName(dest));
	auto raw = readText(srcPath);
	auto txt = printHostModule(a.dest, srcSvelteRel.replace(`\`, `/`), raw, a);
	if (a.rejectedImports.length && a.detail.length)
		a.detail ~= "; rejected " ~ a.rejectedImports.join(",");
	else if (a.rejectedImports.length)
		a.detail = "rejected " ~ a.rejectedImports.join(",");
	a.errorHandler = canFind(raw, "handleError") || canFind(txt, "handleError");
	writeIfChanged(dest, txt, DestCell.host);
	string err;
	if (!parseDFragment(txt, dest, err))
	{
		a.ok = false;
		a.detail = err;
	}
	else if (a.errorHandler)
		a.detail = "vibe0-errorPageHandler";
	else
		a.detail = a.wrapped ? "vibe0-webinterface" : "vibe0-fallthrough";
	return a;
}

/// Hang printed PageServer (etc.) on golden vibe.0 app.d. Prefix keeps Vite on `/`.
void assembleHostRoutes(string ws, HostAttach[] atts)
{
	auto path = buildPath(ws, "webserver", "source", "app.d");
	if (!exists(path) || !atts.length)
		return;
	string imps;
	string regs;
	string errs;
	bool[string] seen;
	foreach (a; atts)
	{
		if (!a.dest.length || !a.className.length)
			continue;
		if (a.className in seen)
			continue;
		seen[a.className] = true;
		imps ~= "import " ~ a.modName ~ ";\n";
		if (a.errorHandler)
		{
			errs ~= "\tsettings.errorPageHandler = (HTTPServerRequest req, HTTPServerResponse res, HTTPServerErrorInfo error) {\n";
			errs ~= "\t\tauto hooks = new " ~ a.className ~ ";\n";
			errs ~= "\t\thooks.handleError(req, res, error);\n";
			errs ~= "\t};\n";
		}
		if (a.kind == "hooks")
			continue;
		regs ~= "\t{\n";
		regs ~= "\t\tWebInterfaceSettings kit = new WebInterfaceSettings;\n";
		regs ~= "\t\tkit.urlPrefix = \"/__svelte-d/host/\";\n";
		regs ~= "\t\trouter.registerWebInterface(new " ~ a.className ~ ", kit);\n";
		regs ~= "\t}\n";
	}
	if (!imps.length)
		return;
	auto src = readText(path);
	src = replaceMarked(src, "// svelte-d:begin-host-imports", "// svelte-d:end-host-imports",
		imps, "import helpers;");
	src = replaceMarked(src, "// svelte-d:begin-host-routes", "// svelte-d:end-host-routes",
		regs, "router.registerWebInterface(new InstallationAPI, isettings);");
	if (errs.length)
		src = replaceMarked(src, "// svelte-d:begin-host-error", "// svelte-d:end-host-error",
			errs, "HTTPServerSettings settings = new HTTPServerSettings;");
	writeIfChanged(path, src, DestCell.host);
}

string printHostModule(string destRel, string srcRel, string raw, ref HostAttach a)
{
	auto body = stripModuleDecl(raw);
	auto peeled = peelAuthorImports(body, ImportCell.host);
	a.authorImports = keptMods(peeled);
	a.rejectedImports = rejectedMods(peeled);
	body = emitImportBlock(peeled) ~ peeled.body;
	a.wrapped = !canFind(body, "class ");
	auto acc = appender!string();
	acc ~= "// Generated by svelte-d from " ~ srcRel ~ "\n";
	acc ~= "// vibe.0 registerWebInterface — host cell (not wasm, not libwasm).\n";
	acc ~= "// Third-party imports use the engine graph (helpers / vibe.db / botan / std).\n";
	acc ~= "// Do not edit — compile will overwrite.\n";
	acc ~= "module " ~ a.modName ~ ";\n\n";
	if (a.wrapped)
	{
		if (!canFind(body, "import vibe.http.server") && !canFind(body, "import vibe.d"))
			acc ~= "import vibe.http.server;\n";
		if (!canFind(body, "import vibe.web.web") && !canFind(body, "import vibe.d"))
			acc ~= "import vibe.web.web;\n";
		acc ~= bodyImportsThenClass(body, a.className);
	}
	else
		acc ~= body;
	if (acc.data.length && acc.data[$ - 1] != '\n')
		acc ~= "\n";
	return acc.data;
}

private string stripModuleDecl(string raw)
{
	auto lines = splitLinesKeep(raw);
	string[] keep;
	bool stripped;
	foreach (ln; lines)
	{
		auto t = ln.strip;
		if (!stripped && t.startsWith("module ") && t.canFind(";"))
		{
			stripped = true;
			continue;
		}
		keep ~= ln;
	}
	return keep.join("\n").strip;
}

private string bodyImportsThenClass(string body, string cls)
{
	auto lines = splitLinesKeep(body);
	string imps;
	string rest;
	bool inHeader = true;
	foreach (ln; lines)
	{
		auto t = ln.strip;
		if (inHeader && (t.startsWith("import ") || t.startsWith("//") || !t.length
				|| t.startsWith("/*") || t.startsWith("*") || t.startsWith("*/")))
		{
			imps ~= ln ~ "\n";
			continue;
		}
		inHeader = false;
		rest ~= ln ~ "\n";
	}
	auto acc = appender!string();
	acc ~= imps;
	if (imps.length && imps[$ - 1] != '\n')
		acc ~= "\n";
	acc ~= "\nclass " ~ cls ~ "\n{\n";
	foreach (ln; splitLinesKeep(rest.strip))
	{
		if (!ln.length)
			acc ~= "\n";
		else
			acc ~= "\t" ~ ln ~ "\n";
	}
	acc ~= "}\n";
	return acc.data;
}

private string[] splitLinesKeep(string s)
{
	string[] o;
	size_t i;
	foreach (j, c; s)
	{
		if (c == '\n')
		{
			auto line = s[i .. j];
			if (line.length && line[$ - 1] == '\r')
				line = line[0 .. $ - 1];
			o ~= line;
			i = j + 1;
		}
	}
	if (i <= s.length)
	{
		auto line = s[i .. $];
		if (line.length && line[$ - 1] == '\r')
			line = line[0 .. $ - 1];
		if (line.length || o.length == 0)
			o ~= line;
	}
	return o;
}

private string moduleFromHostDest(string dest)
{
	auto s = dest.replace(`\`, `/`);
	enum pfx = "webserver/source/";
	if (s.length > pfx.length && s[0 .. pfx.length] == pfx)
		s = s[pfx.length .. $];
	s = stripExtension(s);
	string mod;
	foreach (part; splitSlash(s))
	{
		if (!part.length)
			continue;
		if (mod.length)
			mod ~= ".";
		mod ~= identPart(part);
	}
	return mod.length ? mod : "generated.host";
}

private string[] splitSlash(string s)
{
	string[] outp;
	size_t i;
	foreach (j, c; s)
	{
		if (c == '/')
		{
			outp ~= s[i .. j];
			i = j + 1;
		}
	}
	outp ~= s[i .. $];
	return outp;
}

private string identPart(string part)
{
	string s;
	foreach (c; part)
	{
		if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_')
			s ~= c;
		else
			s ~= '_';
	}
	if (!s.length)
		s = "x";
	if (s[0] >= '0' && s[0] <= '9')
		s = "m_" ~ s;
	return s;
}

/// `…/generated/routes/page_server.d` → `PageServer`;
/// `…/generated/routes/board/page_server.d` → `BoardPageServer`.
private string classFromHostDest(string dest)
{
	auto s = dest.replace(`\`, `/`);
	enum pre = "webserver/source/generated/";
	if (s.length > pre.length && s[0 .. pre.length] == pre)
		s = s[pre.length .. $];
	if (s.length > 2 && s[$ - 2 .. $] == ".d")
		s = s[0 .. $ - 2];
	if (s.length >= 7 && s[0 .. 7] == "routes/")
		s = s[7 .. $];
	return pascalIdent(s);
}

private string pascalIdent(string s)
{
	string o;
	bool up = true;
	foreach (c; s)
	{
		if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')))
		{
			up = true;
			continue;
		}
		if (up)
		{
			if (c >= 'a' && c <= 'z')
				o ~= cast(char)(c - 32);
			else
				o ~= c;
			up = false;
		}
		else
			o ~= c;
	}
	return o.length ? o : "Host";
}

private string replaceMarked(string src, string begin, string end, string inner, string afterAnchor)
{
	auto block = begin ~ "\n" ~ inner ~ end ~ "\n";
	auto b = src.indexOf(begin);
	auto e = src.indexOf(end);
	if (b >= 0 && e > b)
	{
		auto afterEnd = e + end.length;
		if (afterEnd < src.length && src[afterEnd] == '\n')
			afterEnd++;
		return src[0 .. b] ~ block ~ src[afterEnd .. $];
	}
	auto a = src.indexOf(afterAnchor);
	if (a < 0)
		return src ~ "\n" ~ block;
	auto ins = a + afterAnchor.length;
	return src[0 .. ins] ~ "\n" ~ block ~ src[ins .. $];
}
