// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
//
// $app/environment, $app/paths, $env/static/{public,private} → generated
// D enums. PUBLIC_* both cells; other keys host-only. Wasm importing
// env_static_private is a graph error (not a third runtime).
module svelte_d.print.kit_env;

import std.algorithm : canFind, startsWith;
import std.array : appender;
import std.file : dirEntries, exists, mkdirRecurse, readText, SpanMode, write;
import std.path : baseName, buildPath, dirName;
import std.string : indexOf, strip, replace;
import svelte_d.parse.dlang;
import svelte_d.workspace.files;

struct EnvPair
{
	string key;
	string value;
	bool pub;
}

/// Read ws/.env (KEY=VALUE). Missing file still yields PUBLIC_APP_NAME.
EnvPair[] loadKitEnv(string ws)
{
	EnvPair[] outp;
	bool havePublicName;
	auto path = buildPath(ws, ".env");
	if (exists(path))
	{
		foreach (ln; splitLinesKeep(readText(path)))
		{
			auto t = ln.strip;
			if (!t.length || t[0] == '#')
				continue;
			auto eq = t.indexOf('=');
			if (eq <= 0)
				continue;
			auto key = t[0 .. eq].strip;
			auto val = t[eq + 1 .. $].strip;
			if (!isIdent(key))
				continue;
			if (val.length >= 2 && ((val[0] == '"' && val[$ - 1] == '"')
					|| (val[0] == '\'' && val[$ - 1] == '\'')))
				val = val[1 .. $ - 1];
			auto pub = key.startsWith("PUBLIC_");
			outp ~= EnvPair(key, val, pub);
			if (key == "PUBLIC_APP_NAME")
				havePublicName = true;
		}
	}
	if (!havePublicName)
		outp ~= EnvPair("PUBLIC_APP_NAME", "svelte-engine", true);
	return outp;
}

/// Write wasm + host $app / $env modules. Returns a parse error or "".
string writeKitEnv(string ws)
{
	auto pairs = loadKitEnv(ws);
	string err;
	void put(string destRel, string txt)
	{
		if (err.length)
			return;
		auto abs = buildPath(ws, destRel);
		mkdirRecurse(dirName(abs));
		auto cell = destRel.length >= 9 && destRel[0 .. 9] == "webserver"
			? DestCell.host : DestCell.wasm;
		writeIfChanged(abs, txt, cell);
		string e;
		if (!parseDFragment(txt, abs, e))
			err = e;
	}

	put("src-d/kit/app_environment.d", envModule(
		"kit.app_environment", "wasm", true, false, true));
	put("src-d/kit/app_paths.d", pathsModule("kit.app_paths", "wasm"));
	put("src-d/kit/app_navigation.d", navModule("kit.app_navigation", "wasm"));
	put("src-d/kit/env_static_public.d", envConsts(
		"kit.env_static_public", "wasm", pairs, true));

	put("webserver/source/generated/kit/app_environment.d", envModule(
		"generated.kit.app_environment", "host", false, true, true));
	put("webserver/source/generated/kit/app_paths.d", pathsModule(
		"generated.kit.app_paths", "host"));
	put("webserver/source/generated/kit/app_navigation.d", navModule(
		"generated.kit.app_navigation", "host"));
	put("webserver/source/generated/kit/env_static_public.d", envConsts(
		"generated.kit.env_static_public", "host", pairs, true));
	put("webserver/source/generated/kit/env_static_private.d", envConsts(
		"generated.kit.env_static_private", "host", pairs, false));
	return err;
}

/// Wasm src-d must not import host-only $env/static/private.
string checkPrivateLeak(string ws)
{
	auto srcD = buildPath(ws, "src-d");
	if (!exists(srcD))
		return null;
	foreach (e; dirEntries(srcD, SpanMode.depth))
	{
		if (!e.isFile || e.name.length < 2 || e.name[$ - 2 .. $] != ".d")
			continue;
		auto txt = readText(e.name);
		if (canFind(txt, "env_static_private") || canFind(txt, "$env/static/private"))
			return "wasm leaked $env/static/private: " ~ e.name;
	}
	return null;
}

private string envModule(string mod, string cell, bool browser, bool server, bool dev)
{
	auto acc = appender!string();
	acc ~= "// Generated by svelte-d — $app/environment (" ~ cell ~ " cell).\n";
	acc ~= "module " ~ mod ~ ";\n\n";
	acc ~= "enum bool browser = " ~ (browser ? "true" : "false") ~ ";\n";
	acc ~= "enum bool server = " ~ (server ? "true" : "false") ~ ";\n";
	acc ~= "enum bool dev = " ~ (dev ? "true" : "false") ~ ";\n";
	return acc.data;
}

private string pathsModule(string mod, string cell)
{
	auto acc = appender!string();
	acc ~= "// Generated by svelte-d — $app/paths (" ~ cell ~ " cell).\n";
	acc ~= "module " ~ mod ~ ";\n\n";
	acc ~= "enum string base = \"\";\n";
	acc ~= "enum string assets = \"\";\n";
	return acc.data;
}

/// `$app/navigation` goto. D reserved word `goto` → `gotoUrl`.
/// Wasm: libwasm `router().navigateTo`. Host: vibe.0 `res.redirect` is per-request;
/// this module only documents the client mapping.
private string navModule(string mod, string cell)
{
	auto acc = appender!string();
	acc ~= "// Generated by svelte-d — $app/navigation (" ~ cell ~ " cell).\n";
	acc ~= "// Kit `goto` is D-illegal; call `gotoUrl`. invalidate* stay a libwasm seam.\n";
	acc ~= "module " ~ mod ~ ";\n\n";
	if (cell == "wasm")
	{
		acc ~= "import libwasm;\n\n";
		acc ~= "void gotoUrl(string href) @trusted nothrow\n";
		acc ~= "{\n";
		acc ~= "  if (href.length)\n";
		acc ~= "    router().navigateTo(href);\n";
		acc ~= "}\n";
	}
	else
	{
		acc ~= "// Host: use HTTPServerResponse.redirect. Not a second router.\n";
		acc ~= "void gotoUrl(string href) { }\n";
	}
	return acc.data;
}

private string envConsts(string mod, string cell, EnvPair[] pairs, bool pub)
{
	auto acc = appender!string();
	acc ~= "// Generated by svelte-d — $env/static/" ~ (pub ? "public" : "private")
		~ " (" ~ cell ~ " cell).\n";
	acc ~= "module " ~ mod ~ ";\n\n";
	bool any;
	foreach (p; pairs)
	{
		if (p.pub != pub)
			continue;
		acc ~= "enum string " ~ p.key ~ " = " ~ dString(p.value) ~ ";\n";
		any = true;
	}
	if (!any)
		acc ~= "// (no " ~ (pub ? "PUBLIC_*" : "private") ~ " keys)\n";
	return acc.data;
}

private string dString(string s)
{
	string o = "\"";
	foreach (c; s)
	{
		if (c == '\\' || c == '"')
			o ~= '\\';
		o ~= c;
	}
	o ~= "\"";
	return o;
}

private bool isIdent(string s)
{
	if (!s.length)
		return false;
	auto c0 = s[0];
	if (!((c0 >= 'A' && c0 <= 'Z') || (c0 >= 'a' && c0 <= 'z') || c0 == '_'))
		return false;
	foreach (c; s[1 .. $])
	{
		if (!((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')
				|| (c >= '0' && c <= '9') || c == '_'))
			return false;
	}
	return true;
}

private string[] splitLinesKeep(string s)
{
	string[] o;
	size_t i;
	foreach (j, c; s)
	{
		if (c == '\n')
		{
			auto line = s[i .. j];
			if (line.length && line[$ - 1] == '\r')
				line = line[0 .. $ - 1];
			o ~= line;
			i = j + 1;
		}
	}
	if (i <= s.length)
	{
		auto line = s[i .. $];
		if (line.length && line[$ - 1] == '\r')
			line = line[0 .. $ - 1];
		if (line.length || o.length == 0)
			o ~= line;
	}
	return o;
}
