// Copyright (c) 2026 Etienne Cimon
// SPDX-License-Identifier: MIT
//
// Kit filesystem → libwasm URLRouter patterns (router.d).
// [slug] → :slug, (groups) stripped, [[optional]] expands to two
// registrations, layouts are not route entries.
module svelte_d.print.kit_router;

import std.array : appender;
import std.file : exists, mkdirRecurse, readText, write;
import std.path : baseName, buildPath, relativePath, stripExtension;
import std.string : format, indexOf, replace;
import svelte_d.parse.kit_fs;
import svelte_d.fallthrough;
import svelte_d.parse.dlang;
import svelte_d.workspace.files;

struct KitRoute
{
	string kitRel;
	string pattern;
	string srcD;
}

/// `:id` / `:slug` in a libwasm pattern.
private string[] colonParams(string pattern)
{
	string[] o;
	size_t i;
	while (i < pattern.length)
	{
		if (pattern[i] != ':')
		{
			i++;
			continue;
		}
		i++;
		string n;
		while (i < pattern.length && ((pattern[i] >= 'a' && pattern[i] <= 'z')
				|| (pattern[i] >= 'A' && pattern[i] <= 'Z')
				|| (pattern[i] >= '0' && pattern[i] <= '9') || pattern[i] == '_'))
		{
			n ~= pattern[i];
			i++;
		}
		if (n.length)
			o ~= n;
	}
	return o;
}

KitRoute[] collectKitRoutes(string srcSvelte)
{
	auto acc = appender!(KitRoute[]);
	bool[string] seen;
	foreach (k; walkKit(srcSvelte))
	{
		if (k.kind != "page")
			continue;
		auto rel = relativePath(k.path, srcSvelte).replace(`\`, `/`);
		auto dest = mapKitRel(rel).srcD;
		foreach (pat; kitToPatterns(rel))
		{
			if (!pat.length || pat in seen)
				continue;
			seen[pat] = true;
			KitRoute r;
			r.kitRel = rel;
			r.pattern = pat;
			r.srcD = dest;
			acc ~= r;
		}
	}
	return acc.data;
}

private struct KitChild
{
	string dest;
	string field;
	string typeFqn;
	string modName;
	bool layout;
}

private KitChild[] collectKitPages(KitRoute[] rs)
{
	auto acc = appender!(KitChild[]);
	bool[string] seen;
	foreach (r; rs)
	{
		if (!r.srcD.length || r.srcD in seen)
			continue;
		seen[r.srcD] = true;
		acc ~= makeChild(r.srcD, false);
	}
	return acc.data;
}

private KitChild[] collectKitLayouts(string srcSvelte)
{
	auto acc = appender!(KitChild[]);
	bool[string] seen;
	foreach (k; walkKit(srcSvelte))
	{
		if (k.kind != "layout")
			continue;
		auto rel = relativePath(k.path, srcSvelte).replace(`\`, `/`);
		auto dest = mapKitRel(rel).srcD;
		if (!dest.length || dest in seen)
			continue;
		seen[dest] = true;
		acc ~= makeChild(dest, true);
	}
	return acc.data;
}

private KitChild makeChild(string dest, bool layout)
{
	KitChild c;
	c.dest = dest.replace(`\`, `/`);
	c.layout = layout;
	c.modName = moduleFromDest(c.dest);
	auto type = pascalIdent(stripExtension(baseName(c.dest)));
	c.typeFqn = c.modName ~ "." ~ type;
	c.field = fieldFromDest(c.dest);
	return c;
}

private string fieldFromDest(string dest)
{
	auto s = dest.replace(`\`, `/`);
	enum pfx = "src-d/routes/";
	if (s.length >= pfx.length && s[0 .. pfx.length] == pfx)
		s = s[pfx.length .. $];
	else if (s.length >= 6 && s[0 .. 6] == "src-d/")
		s = s[6 .. $];
	s = stripExtension(s);
	if (s == "page")
		return "rootPage";
	if (s == "layout")
		return "rootLayout";
	return camelIdent(pascalIdent(identFromRel(s)));
}

private string layoutFieldForPage(KitChild[] layouts, string pageDest)
{
	string best;
	size_t bestLen;
	auto pd = dirOf(pageDest) ~ "/";
	foreach (l; layouts)
	{
		auto ld = dirOf(l.dest) ~ "/";
		if (pd.length >= ld.length && pd[0 .. ld.length] == ld && ld.length > bestLen)
		{
			best = l.field;
			bestLen = ld.length;
		}
	}
	return best;
}

private string dirOf(string dest)
{
	auto s = dest.replace(`\`, `/`);
	auto slash = lastSlash(s);
	if (slash <= 0)
		return s;
	return s[0 .. slash];
}

private int lastSlash(string s)
{
	foreach_reverse (i, c; s)
		if (c == '/')
			return cast(int) i;
	return -1;
}

private KitChild[] orphansOf(KitChild[] pages, KitChild[] layouts)
{
	auto acc = appender!(KitChild[]);
	foreach (p; pages)
		if (!layoutFieldForPage(layouts, p.dest).length)
			acc ~= p;
	return acc.data;
}

private KitChild[] pagesOnLayout(KitChild[] pages, KitChild[] layouts, string layField)
{
	auto acc = appender!(KitChild[]);
	foreach (p; pages)
		if (layoutFieldForPage(layouts, p.dest) == layField)
			acc ~= p;
	return acc.data;
}

string kitRouterSource(KitRoute[] rs, KitChild[] layouts, KitChild[] pages)
{
	auto orphans = orphansOf(pages, layouts);
	auto acc = appender!string();
	acc ~= "// Generated by svelte-d — SvelteKit files → libwasm URLRouter.\n";
	acc ~= "// registerRoutes / navigateTo / setBasePath live in libwasm.router.\n";
	acc ~= "// T5: @entering remounts the matching page. Slotted pages are @child of the layout.\n";
	acc ~= "module svelte_engine.kit_router;\n\n";
	acc ~= "import libwasm;\n";
	bool[string] imported;
	foreach (c; layouts)
		if (c.modName !in imported)
		{
			imported[c.modName] = true;
			acc ~= "import " ~ c.modName ~ ";\n";
		}
	foreach (c; orphans)
		if (c.modName !in imported)
		{
			imported[c.modName] = true;
			acc ~= "import " ~ c.modName ~ ";\n";
		}
	acc ~= "\nnothrow:\n@safe:\n\n";
	acc ~= "struct KitRoutes\n{\nnothrow:\n  @trusted:\n";
	foreach (c; layouts)
	{
		acc ~= "  @child " ~ c.typeFqn ~ " " ~ c.field ~ ";\n";
		acc ~= "  @visible!\"" ~ c.field ~ "\" bool show_" ~ c.field ~ " = false;\n";
	}
	foreach (c; orphans)
	{
		acc ~= "  @child " ~ c.typeFqn ~ " " ~ c.field ~ ";\n";
		acc ~= "  @visible!\"" ~ c.field ~ "\" bool show_" ~ c.field ~ " = false;\n";
	}
	acc ~= "\n";
	foreach (r; rs)
	{
		auto name = "enter_" ~ identFromRel(r.pattern);
		auto pageField = fieldFromDest(r.srcD);
		auto layField = layoutFieldForPage(layouts, r.srcD);
		acc ~= format("  @entering!\"%s\"\n", r.pattern);
		acc ~= format("  Optional!(Promise!void) %s(ref RouterEvent ev)\n", name);
		acc ~= "  {\n";
		foreach (c; layouts)
			acc ~= "    setVisible!\"" ~ c.field ~ "\"(this, " ~ (c.field == layField ? "true" : "false") ~ ");\n";
		if (layField.length)
		{
			foreach (p; pagesOnLayout(pages, layouts, layField))
				acc ~= "    setVisible!\"" ~ p.field ~ "\"(" ~ layField ~ ", " ~ (p.field == pageField
						? "true" : "false") ~ ");\n";
			acc ~= "    setVisible!\"slot_default\"(" ~ layField ~ ", false);\n";
		}
		foreach (c; orphans)
			acc ~= "    setVisible!\"" ~ c.field ~ "\"(this, " ~ (c.field == pageField ? "true" : "false") ~ ");\n";
		auto owner = layField.length ? layField ~ "." ~ pageField : pageField;
		foreach (pn; colonParams(r.pattern))
		{
			acc ~= "    {\n";
			acc ~= "      auto _p = ev.parameters[\"" ~ pn ~ "\"];\n";
			acc ~= "      " ~ owner ~ "." ~ pn ~ " = _p;\n";
			acc ~= "      " ~ owner ~ ".applyKitParams();\n";
			acc ~= "    }\n";
		}
		acc ~= "    return typeof(return).init;\n";
		acc ~= "  }\n\n";
	}
	acc ~= "  mixin NodeDef!\"div\";\n";
	acc ~= "}\n";
	return acc.data;
}

/// Write ws/src-d/kit_router.d. Returns dest or "" if nothing to write.
string writeKitRouter(string ws, out string err)
{
	auto srcSvelte = buildPath(ws, "src-svelte");
	auto rs = collectKitRoutes(srcSvelte);
	auto layouts = collectKitLayouts(srcSvelte);
	auto pages = collectKitPages(rs);
	auto dest = buildPath(ws, "src-d", "kit_router.d");
	mkdirRecurse(buildPath(ws, "src-d"));
	auto txt = kitRouterSource(rs, layouts, pages);
	writeIfChanged(dest, txt, DestCell.wasm);
	assembleSlotPages(ws, layouts, pages);
	if (!parseDFragment(txt, dest, err))
		return dest;
	err = null;
	return dest;
}

/// Hang covered pages as @child of their layout (slot projection). Idempotent.
void assembleSlotPages(string ws, KitChild[] layouts, KitChild[] pages)
{
	foreach (l; layouts)
	{
		auto kids = pagesOnLayout(pages, layouts, l.field);
		if (!kids.length)
			continue;
		auto path = buildPath(ws, l.dest);
		if (!exists(path))
			continue;
		string imps;
		bool[string] seen;
		foreach (p; kids)
		{
			if (p.modName in seen)
				continue;
			seen[p.modName] = true;
			imps ~= "import " ~ p.modName ~ ";\n";
		}
		string fields;
		foreach (p; kids)
		{
			fields ~= "  @child " ~ p.typeFqn ~ " " ~ p.field ~ ";\n";
			fields ~= "  @visible!\"" ~ p.field ~ "\" bool show_" ~ p.field ~ " = false;\n";
		}
		auto src = readText(path);
		src = replaceMarked(src, "// svelte-d:begin-slot-import", "// svelte-d:end-slot-import",
			imps, "import libwasm;");
		auto pageAnchor = src.indexOf(`mixin Slot!"default_";`) >= 0
			? `mixin Slot!"default_";` : `mixin NodeDef!"div";`;
		src = replaceMarked(src, "// svelte-d:begin-slot-pages", "// svelte-d:end-slot-pages",
			fields, pageAnchor);
		writeIfChanged(path, src, DestCell.wasm);
	}
}

/// Hang KitRoutes on golden App so registerRoutes sees @entering. Idempotent.
void assembleKitOnApp(string ws)
{
	auto path = buildPath(ws, "src-d", "app.d");
	auto kr = buildPath(ws, "src-d", "kit_router.d");
	if (!exists(path) || !exists(kr))
		return;
	auto src = readText(path);
	src = replaceMarked(src, "// svelte-d:begin-kit-import", "// svelte-d:end-kit-import",
		"import svelte_engine.kit_router;\n", "import jshost;");
	auto childAnchor = src.indexOf("// svelte-d:end-children") >= 0
		? "// svelte-d:end-children" : "  @child Dock dock;";
	src = replaceMarked(src, "// svelte-d:begin-kit-child", "// svelte-d:end-kit-child",
		"  @child KitRoutes kitRoutes;\n", childAnchor);
	writeIfChanged(path, src, DestCell.wasm);
}

private string moduleFromDest(string dest)
{
	auto s = dest.replace(`\`, `/`);
	if (s.length >= 6 && s[0 .. 6] == "src-d/")
		s = s[6 .. $];
	s = stripExtension(s);
	string mod;
	foreach (part; splitSlash(s))
	{
		if (!part.length)
			continue;
		if (mod.length)
			mod ~= ".";
		mod ~= identPart(part);
	}
	return mod.length ? mod : "app";
}

private string[] splitSlash(string s)
{
	string[] outp;
	size_t i;
	foreach (j, c; s)
	{
		if (c == '/')
		{
			outp ~= s[i .. j];
			i = j + 1;
		}
	}
	outp ~= s[i .. $];
	return outp;
}

private string identPart(string part)
{
	string s;
	foreach (c; part)
	{
		if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_')
			s ~= c;
		else
			s ~= '_';
	}
	if (!s.length)
		s = "x";
	if (s[0] >= '0' && s[0] <= '9')
		s = "m_" ~ s;
	return s;
}

private string pascalIdent(string s)
{
	string o;
	bool up = true;
	foreach (c; s)
	{
		if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')))
		{
			up = true;
			continue;
		}
		if (up)
		{
			if (c >= 'a' && c <= 'z')
				o ~= cast(char)(c - 32);
			else
				o ~= c;
			up = false;
		}
		else
			o ~= c;
	}
	return o.length ? o : "Comp";
}

private string camelIdent(string pascal)
{
	if (!pascal.length)
		return pascal;
	char f = pascal[0];
	if (f >= 'A' && f <= 'Z')
		f = cast(char)(f + 32);
	return cast(string)(f ~ pascal[1 .. $]);
}

private string replaceMarked(string src, string begin, string end, string inner, string afterAnchor)
{
	auto block = begin ~ "\n" ~ inner ~ end ~ "\n";
	auto b = src.indexOf(begin);
	auto e = src.indexOf(end);
	if (b >= 0 && e > b)
	{
		auto afterEnd = e + end.length;
		if (afterEnd < src.length && src[afterEnd] == '\n')
			afterEnd++;
		return src[0 .. b] ~ block ~ src[afterEnd .. $];
	}
	auto a = src.indexOf(afterAnchor);
	if (a < 0)
		return src ~ "\n" ~ block;
	auto ins = a + afterAnchor.length;
	return src[0 .. ins] ~ "\n" ~ block ~ src[ins .. $];
}
