/+ DO NOT EDIT BY HAND!
This module was automatically generated from the following grammar:

SvelteKit:
  Name <~ [A-Za-z_] [A-Za-z0-9_]*
  TagName <~ [A-Za-z] [A-Za-z0-9-]*
  VoidName <- "input" / "br" / "hr" / "img" / "meta" / "link" / "area" / "col" / "source" / "wbr" / "base"
  Quoted <~ doublequote (!doublequote .)* doublequote / "'" (!"'" .)* "'"
  AttrName <~ [A-Za-z:@] [-A-Za-z0-9:._]*
  Mustache < "{" Name "}"
  AttrValue < Mustache / Quoted
  Attr < Spacing AttrName (Spacing "=" Spacing AttrValue)?
  Text <~ (!("<" / "{") .)+
  Spacing <- (blank / endOfLine)*

  ScriptHead <~ (!">" .)*
  ScriptBody <~ (!"</script>" .)*
  StyleBody <~ (!"</style>" .)*
  ScriptBlock < "<script" ScriptHead ">" ScriptBody "</script>" Spacing
  StyleBlock < "<style" ScriptHead ">" StyleBody "</style>" Spacing
  HtmlComment < "<!--" (!"-->" .)* "-->" Spacing

  IfCond <~ (!"}" .)+
  EachList <~ Name

  VoidElement < "<" VoidName Attr* Spacing ("/>" / ">") Spacing
  OpenElement < "<" !("script" / "style" / "/") TagName Attr* Spacing ">" MarkupNode* "</" TagName Spacing ">" Spacing
  Element < VoidElement / OpenElement

  ElsePart < "{:else}" MarkupNode*
  IfBlock < "{#if" Spacing IfCond "}" MarkupNode* ElsePart? "{/if}" Spacing
  EachBlock < "{#each" Spacing EachList Spacing "as" Spacing Name Spacing "}" MarkupNode* "{/each}" Spacing

  MarkupNode < IfBlock / EachBlock / Element / Mustache / HtmlComment / Text
  MarkupDoc < Spacing MarkupNode* eoi
  FilePart < ScriptBlock / StyleBlock / HtmlComment / MarkupNode
  Document < Spacing FilePart* eoi


+/
module svelte_d.grammar.sveltekit;

// Generated by grammar/generator. Source of truth: grammar/sveltekit.peg.
// mixin(grammar) overflows LDC 1.42 + Pegged 0.4.9; this module is asModule.

public import pegged.peg;
import std.algorithm: startsWith;
import std.functional: toDelegate;

@safe struct GenericSvelteKit(TParseTree)
{
    import std.functional : toDelegate;
    import pegged.dynamic.grammar;
    static import pegged.peg;
    struct SvelteKit
    {
    enum name = "SvelteKit";
    static ParseTree delegate(ParseTree) @safe [string] before;
    static ParseTree delegate(ParseTree) @safe [string] after;
    static ParseTree delegate(ParseTree) @safe [string] rules;
    static this() @trusted
    {
        rules["Name"] = toDelegate(&Name);
        rules["TagName"] = toDelegate(&TagName);
        rules["VoidName"] = toDelegate(&VoidName);
        rules["Quoted"] = toDelegate(&Quoted);
        rules["AttrName"] = toDelegate(&AttrName);
        rules["Mustache"] = toDelegate(&Mustache);
        rules["AttrValue"] = toDelegate(&AttrValue);
        rules["Attr"] = toDelegate(&Attr);
        rules["Text"] = toDelegate(&Text);
        rules["Spacing"] = toDelegate(&Spacing);
    }

    template hooked(alias r, string name)
    {
        static ParseTree hooked(ParseTree p) @safe
        {
            ParseTree result;

            if (name in before)
            {
                result = before[name](p);
                if (result.successful)
                    return result;
            }

            result = r(p);
            if (result.successful || name !in after)
                return result;

            result = after[name](p);
            return result;
        }

        static ParseTree hooked(string input) @safe
        {
            return hooked!(r, name)(ParseTree("",false,[],input));
        }
    }

    static void addRuleBefore(string parentRule, string ruleSyntax) @safe
    {
        // enum name is the current grammar name
        DynamicGrammar dg = pegged.dynamic.grammar.grammar(name ~ ": " ~ ruleSyntax, rules);
        foreach(ruleName,rule; dg.rules)
            if (ruleName != "Spacing") // Keep the local Spacing rule, do not overwrite it
                rules[ruleName] = rule;
        before[parentRule] = rules[dg.startingRule];
    }

    static void addRuleAfter(string parentRule, string ruleSyntax) @safe
    {
        // enum name is the current grammar named
        DynamicGrammar dg = pegged.dynamic.grammar.grammar(name ~ ": " ~ ruleSyntax, rules);
        foreach(ruleName,rule; dg.rules)
        {
            if (ruleName != "Spacing")
                rules[ruleName] = rule;
        }
        after[parentRule] = rules[dg.startingRule];
    }

    static bool isRule(string s) pure nothrow @nogc
    {
        import std.algorithm : startsWith;
        return s.startsWith("SvelteKit.");
    }
    mixin decimateTree;

    static TParseTree Name(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.literal!("_")), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!("_"))))), "SvelteKit.Name")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.literal!("_")), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!("_"))))), "SvelteKit.Name"), "Name")(p);
        }
    }
    static TParseTree Name(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.literal!("_")), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!("_"))))), "SvelteKit.Name")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.literal!("_")), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!("_"))))), "SvelteKit.Name"), "Name")(TParseTree("", false,[], s));
        }
    }
    static string Name(GetName g)
    {
        return "SvelteKit.Name";
    }

    static TParseTree TagName(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z')), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!("-"))))), "SvelteKit.TagName")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z')), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!("-"))))), "SvelteKit.TagName"), "TagName")(p);
        }
    }
    static TParseTree TagName(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z')), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!("-"))))), "SvelteKit.TagName")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z')), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!("-"))))), "SvelteKit.TagName"), "TagName")(TParseTree("", false,[], s));
        }
    }
    static string TagName(GetName g)
    {
        return "SvelteKit.TagName";
    }

    static TParseTree VoidName(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.keywords!("input", "br", "hr", "img", "meta", "link", "area", "col", "source", "wbr", "base"), "SvelteKit.VoidName")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.keywords!("input", "br", "hr", "img", "meta", "link", "area", "col", "source", "wbr", "base"), "SvelteKit.VoidName"), "VoidName")(p);
        }
    }
    static TParseTree VoidName(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.keywords!("input", "br", "hr", "img", "meta", "link", "area", "col", "source", "wbr", "base"), "SvelteKit.VoidName")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.keywords!("input", "br", "hr", "img", "meta", "link", "area", "col", "source", "wbr", "base"), "SvelteKit.VoidName"), "VoidName")(TParseTree("", false,[], s));
        }
    }
    static string VoidName(GetName g)
    {
        return "SvelteKit.VoidName";
    }

    static TParseTree Quoted(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.or!(pegged.peg.and!(doublequote, pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(doublequote), pegged.peg.any)), doublequote), pegged.peg.and!(pegged.peg.literal!("'"), pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("'")), pegged.peg.any)), pegged.peg.literal!("'")))), "SvelteKit.Quoted")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.or!(pegged.peg.and!(doublequote, pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(doublequote), pegged.peg.any)), doublequote), pegged.peg.and!(pegged.peg.literal!("'"), pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("'")), pegged.peg.any)), pegged.peg.literal!("'")))), "SvelteKit.Quoted"), "Quoted")(p);
        }
    }
    static TParseTree Quoted(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.or!(pegged.peg.and!(doublequote, pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(doublequote), pegged.peg.any)), doublequote), pegged.peg.and!(pegged.peg.literal!("'"), pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("'")), pegged.peg.any)), pegged.peg.literal!("'")))), "SvelteKit.Quoted")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.or!(pegged.peg.and!(doublequote, pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(doublequote), pegged.peg.any)), doublequote), pegged.peg.and!(pegged.peg.literal!("'"), pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("'")), pegged.peg.any)), pegged.peg.literal!("'")))), "SvelteKit.Quoted"), "Quoted")(TParseTree("", false,[], s));
        }
    }
    static string Quoted(GetName g)
    {
        return "SvelteKit.Quoted";
    }

    static TParseTree AttrName(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.literal!(":"), pegged.peg.literal!("@")), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.literal!("-"), pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!(":"), pegged.peg.literal!("."), pegged.peg.literal!("_"))))), "SvelteKit.AttrName")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.literal!(":"), pegged.peg.literal!("@")), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.literal!("-"), pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!(":"), pegged.peg.literal!("."), pegged.peg.literal!("_"))))), "SvelteKit.AttrName"), "AttrName")(p);
        }
    }
    static TParseTree AttrName(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.literal!(":"), pegged.peg.literal!("@")), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.literal!("-"), pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!(":"), pegged.peg.literal!("."), pegged.peg.literal!("_"))))), "SvelteKit.AttrName")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.and!(pegged.peg.or!(pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.literal!(":"), pegged.peg.literal!("@")), pegged.peg.zeroOrMore!(pegged.peg.or!(pegged.peg.literal!("-"), pegged.peg.charRange!('A', 'Z'), pegged.peg.charRange!('a', 'z'), pegged.peg.charRange!('0', '9'), pegged.peg.literal!(":"), pegged.peg.literal!("."), pegged.peg.literal!("_"))))), "SvelteKit.AttrName"), "AttrName")(TParseTree("", false,[], s));
        }
    }
    static string AttrName(GetName g)
    {
        return "SvelteKit.AttrName";
    }

    static TParseTree Mustache(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{"), Spacing), pegged.peg.wrapAround!(Spacing, Name, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing)), "SvelteKit.Mustache")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{"), Spacing), pegged.peg.wrapAround!(Spacing, Name, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing)), "SvelteKit.Mustache"), "Mustache")(p);
        }
    }
    static TParseTree Mustache(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{"), Spacing), pegged.peg.wrapAround!(Spacing, Name, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing)), "SvelteKit.Mustache")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{"), Spacing), pegged.peg.wrapAround!(Spacing, Name, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing)), "SvelteKit.Mustache"), "Mustache")(TParseTree("", false,[], s));
        }
    }
    static string Mustache(GetName g)
    {
        return "SvelteKit.Mustache";
    }

    static TParseTree AttrValue(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, Mustache, Spacing), pegged.peg.wrapAround!(Spacing, Quoted, Spacing)), "SvelteKit.AttrValue")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, Mustache, Spacing), pegged.peg.wrapAround!(Spacing, Quoted, Spacing)), "SvelteKit.AttrValue"), "AttrValue")(p);
        }
    }
    static TParseTree AttrValue(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, Mustache, Spacing), pegged.peg.wrapAround!(Spacing, Quoted, Spacing)), "SvelteKit.AttrValue")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, Mustache, Spacing), pegged.peg.wrapAround!(Spacing, Quoted, Spacing)), "SvelteKit.AttrValue"), "AttrValue")(TParseTree("", false,[], s));
        }
    }
    static string AttrValue(GetName g)
    {
        return "SvelteKit.AttrValue";
    }

    static TParseTree Attr(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, AttrName, Spacing), pegged.peg.option!(pegged.peg.wrapAround!(Spacing, pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("="), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, AttrValue, Spacing)), Spacing))), "SvelteKit.Attr")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, AttrName, Spacing), pegged.peg.option!(pegged.peg.wrapAround!(Spacing, pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("="), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, AttrValue, Spacing)), Spacing))), "SvelteKit.Attr"), "Attr")(p);
        }
    }
    static TParseTree Attr(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, AttrName, Spacing), pegged.peg.option!(pegged.peg.wrapAround!(Spacing, pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("="), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, AttrValue, Spacing)), Spacing))), "SvelteKit.Attr")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, AttrName, Spacing), pegged.peg.option!(pegged.peg.wrapAround!(Spacing, pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("="), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, AttrValue, Spacing)), Spacing))), "SvelteKit.Attr"), "Attr")(TParseTree("", false,[], s));
        }
    }
    static string Attr(GetName g)
    {
        return "SvelteKit.Attr";
    }

    static TParseTree Text(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.oneOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.keywords!("<", "{")), pegged.peg.any))), "SvelteKit.Text")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.oneOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.keywords!("<", "{")), pegged.peg.any))), "SvelteKit.Text"), "Text")(p);
        }
    }
    static TParseTree Text(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.oneOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.keywords!("<", "{")), pegged.peg.any))), "SvelteKit.Text")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.oneOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.keywords!("<", "{")), pegged.peg.any))), "SvelteKit.Text"), "Text")(TParseTree("", false,[], s));
        }
    }
    static string Text(GetName g)
    {
        return "SvelteKit.Text";
    }

    static TParseTree Spacing(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.zeroOrMore!(pegged.peg.or!(blank, endOfLine)), "SvelteKit.Spacing")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.zeroOrMore!(pegged.peg.or!(blank, endOfLine)), "SvelteKit.Spacing"), "Spacing")(p);
        }
    }
    static TParseTree Spacing(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.zeroOrMore!(pegged.peg.or!(blank, endOfLine)), "SvelteKit.Spacing")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.zeroOrMore!(pegged.peg.or!(blank, endOfLine)), "SvelteKit.Spacing"), "Spacing")(TParseTree("", false,[], s));
        }
    }
    static string Spacing(GetName g)
    {
        return "SvelteKit.Spacing";
    }

    static TParseTree ScriptHead(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!(">")), pegged.peg.any))), "SvelteKit.ScriptHead")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!(">")), pegged.peg.any))), "SvelteKit.ScriptHead"), "ScriptHead")(p);
        }
    }
    static TParseTree ScriptHead(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!(">")), pegged.peg.any))), "SvelteKit.ScriptHead")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!(">")), pegged.peg.any))), "SvelteKit.ScriptHead"), "ScriptHead")(TParseTree("", false,[], s));
        }
    }
    static string ScriptHead(GetName g)
    {
        return "SvelteKit.ScriptHead";
    }

    static TParseTree ScriptBody(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("</script>")), pegged.peg.any))), "SvelteKit.ScriptBody")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("</script>")), pegged.peg.any))), "SvelteKit.ScriptBody"), "ScriptBody")(p);
        }
    }
    static TParseTree ScriptBody(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("</script>")), pegged.peg.any))), "SvelteKit.ScriptBody")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("</script>")), pegged.peg.any))), "SvelteKit.ScriptBody"), "ScriptBody")(TParseTree("", false,[], s));
        }
    }
    static string ScriptBody(GetName g)
    {
        return "SvelteKit.ScriptBody";
    }

    static TParseTree StyleBody(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("</style>")), pegged.peg.any))), "SvelteKit.StyleBody")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("</style>")), pegged.peg.any))), "SvelteKit.StyleBody"), "StyleBody")(p);
        }
    }
    static TParseTree StyleBody(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("</style>")), pegged.peg.any))), "SvelteKit.StyleBody")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.zeroOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("</style>")), pegged.peg.any))), "SvelteKit.StyleBody"), "StyleBody")(TParseTree("", false,[], s));
        }
    }
    static string StyleBody(GetName g)
    {
        return "SvelteKit.StyleBody";
    }

    static TParseTree ScriptBlock(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<script"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptHead, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptBody, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</script>"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.ScriptBlock")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<script"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptHead, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptBody, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</script>"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.ScriptBlock"), "ScriptBlock")(p);
        }
    }
    static TParseTree ScriptBlock(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<script"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptHead, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptBody, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</script>"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.ScriptBlock")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<script"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptHead, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptBody, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</script>"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.ScriptBlock"), "ScriptBlock")(TParseTree("", false,[], s));
        }
    }
    static string ScriptBlock(GetName g)
    {
        return "SvelteKit.ScriptBlock";
    }

    static TParseTree StyleBlock(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<style"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptHead, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, StyleBody, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</style>"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.StyleBlock")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<style"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptHead, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, StyleBody, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</style>"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.StyleBlock"), "StyleBlock")(p);
        }
    }
    static TParseTree StyleBlock(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<style"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptHead, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, StyleBody, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</style>"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.StyleBlock")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<style"), Spacing), pegged.peg.wrapAround!(Spacing, ScriptHead, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, StyleBody, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</style>"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.StyleBlock"), "StyleBlock")(TParseTree("", false,[], s));
        }
    }
    static string StyleBlock(GetName g)
    {
        return "SvelteKit.StyleBlock";
    }

    static TParseTree HtmlComment(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<!--"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("-->"), Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.any, Spacing)), Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("-->"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.HtmlComment")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<!--"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("-->"), Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.any, Spacing)), Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("-->"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.HtmlComment"), "HtmlComment")(p);
        }
    }
    static TParseTree HtmlComment(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<!--"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("-->"), Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.any, Spacing)), Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("-->"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.HtmlComment")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<!--"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("-->"), Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.any, Spacing)), Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("-->"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.HtmlComment"), "HtmlComment")(TParseTree("", false,[], s));
        }
    }
    static string HtmlComment(GetName g)
    {
        return "SvelteKit.HtmlComment";
    }

    static TParseTree IfCond(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.oneOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("}")), pegged.peg.any))), "SvelteKit.IfCond")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.oneOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("}")), pegged.peg.any))), "SvelteKit.IfCond"), "IfCond")(p);
        }
    }
    static TParseTree IfCond(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.oneOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("}")), pegged.peg.any))), "SvelteKit.IfCond")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(pegged.peg.oneOrMore!(pegged.peg.and!(pegged.peg.negLookahead!(pegged.peg.literal!("}")), pegged.peg.any))), "SvelteKit.IfCond"), "IfCond")(TParseTree("", false,[], s));
        }
    }
    static string IfCond(GetName g)
    {
        return "SvelteKit.IfCond";
    }

    static TParseTree EachList(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.fuse!(Name), "SvelteKit.EachList")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(Name), "SvelteKit.EachList"), "EachList")(p);
        }
    }
    static TParseTree EachList(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.fuse!(Name), "SvelteKit.EachList")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.fuse!(Name), "SvelteKit.EachList"), "EachList")(TParseTree("", false,[], s));
        }
    }
    static string EachList(GetName g)
    {
        return "SvelteKit.EachList";
    }

    static TParseTree VoidElement(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<"), Spacing), pegged.peg.wrapAround!(Spacing, VoidName, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, Attr, Spacing)), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.or!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("/>"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing)), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.VoidElement")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<"), Spacing), pegged.peg.wrapAround!(Spacing, VoidName, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, Attr, Spacing)), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.or!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("/>"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing)), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.VoidElement"), "VoidElement")(p);
        }
    }
    static TParseTree VoidElement(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<"), Spacing), pegged.peg.wrapAround!(Spacing, VoidName, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, Attr, Spacing)), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.or!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("/>"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing)), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.VoidElement")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<"), Spacing), pegged.peg.wrapAround!(Spacing, VoidName, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, Attr, Spacing)), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.or!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("/>"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing)), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.VoidElement"), "VoidElement")(TParseTree("", false,[], s));
        }
    }
    static string VoidElement(GetName g)
    {
        return "SvelteKit.VoidElement";
    }

    static TParseTree OpenElement(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<"), Spacing), pegged.peg.negLookahead!(pegged.peg.wrapAround!(Spacing, pegged.peg.or!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("script"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("style"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("/"), Spacing)), Spacing)), pegged.peg.wrapAround!(Spacing, TagName, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, Attr, Spacing)), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</"), Spacing), pegged.peg.wrapAround!(Spacing, TagName, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.OpenElement")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<"), Spacing), pegged.peg.negLookahead!(pegged.peg.wrapAround!(Spacing, pegged.peg.or!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("script"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("style"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("/"), Spacing)), Spacing)), pegged.peg.wrapAround!(Spacing, TagName, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, Attr, Spacing)), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</"), Spacing), pegged.peg.wrapAround!(Spacing, TagName, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.OpenElement"), "OpenElement")(p);
        }
    }
    static TParseTree OpenElement(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<"), Spacing), pegged.peg.negLookahead!(pegged.peg.wrapAround!(Spacing, pegged.peg.or!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("script"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("style"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("/"), Spacing)), Spacing)), pegged.peg.wrapAround!(Spacing, TagName, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, Attr, Spacing)), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</"), Spacing), pegged.peg.wrapAround!(Spacing, TagName, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.OpenElement")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("<"), Spacing), pegged.peg.negLookahead!(pegged.peg.wrapAround!(Spacing, pegged.peg.or!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("script"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("style"), Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("/"), Spacing)), Spacing)), pegged.peg.wrapAround!(Spacing, TagName, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, Attr, Spacing)), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("</"), Spacing), pegged.peg.wrapAround!(Spacing, TagName, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!(">"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.OpenElement"), "OpenElement")(TParseTree("", false,[], s));
        }
    }
    static string OpenElement(GetName g)
    {
        return "SvelteKit.OpenElement";
    }

    static TParseTree Element(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, VoidElement, Spacing), pegged.peg.wrapAround!(Spacing, OpenElement, Spacing)), "SvelteKit.Element")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, VoidElement, Spacing), pegged.peg.wrapAround!(Spacing, OpenElement, Spacing)), "SvelteKit.Element"), "Element")(p);
        }
    }
    static TParseTree Element(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, VoidElement, Spacing), pegged.peg.wrapAround!(Spacing, OpenElement, Spacing)), "SvelteKit.Element")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, VoidElement, Spacing), pegged.peg.wrapAround!(Spacing, OpenElement, Spacing)), "SvelteKit.Element"), "Element")(TParseTree("", false,[], s));
        }
    }
    static string Element(GetName g)
    {
        return "SvelteKit.Element";
    }

    static TParseTree ElsePart(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{:else}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing))), "SvelteKit.ElsePart")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{:else}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing))), "SvelteKit.ElsePart"), "ElsePart")(p);
        }
    }
    static TParseTree ElsePart(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{:else}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing))), "SvelteKit.ElsePart")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{:else}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing))), "SvelteKit.ElsePart"), "ElsePart")(TParseTree("", false,[], s));
        }
    }
    static string ElsePart(GetName g)
    {
        return "SvelteKit.ElsePart";
    }

    static TParseTree IfBlock(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{#if"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, IfCond, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.option!(pegged.peg.wrapAround!(Spacing, ElsePart, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{/if}"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.IfBlock")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{#if"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, IfCond, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.option!(pegged.peg.wrapAround!(Spacing, ElsePart, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{/if}"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.IfBlock"), "IfBlock")(p);
        }
    }
    static TParseTree IfBlock(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{#if"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, IfCond, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.option!(pegged.peg.wrapAround!(Spacing, ElsePart, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{/if}"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.IfBlock")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{#if"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, IfCond, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.option!(pegged.peg.wrapAround!(Spacing, ElsePart, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{/if}"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.IfBlock"), "IfBlock")(TParseTree("", false,[], s));
        }
    }
    static string IfBlock(GetName g)
    {
        return "SvelteKit.IfBlock";
    }

    static TParseTree EachBlock(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{#each"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, EachList, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("as"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, Name, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{/each}"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.EachBlock")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{#each"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, EachList, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("as"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, Name, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{/each}"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.EachBlock"), "EachBlock")(p);
        }
    }
    static TParseTree EachBlock(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{#each"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, EachList, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("as"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, Name, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{/each}"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.EachBlock")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{#each"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, EachList, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("as"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, Name, Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("}"), Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, pegged.peg.literal!("{/each}"), Spacing), pegged.peg.wrapAround!(Spacing, Spacing, Spacing)), "SvelteKit.EachBlock"), "EachBlock")(TParseTree("", false,[], s));
        }
    }
    static string EachBlock(GetName g)
    {
        return "SvelteKit.EachBlock";
    }

    static TParseTree MarkupNode(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, IfBlock, Spacing), pegged.peg.wrapAround!(Spacing, EachBlock, Spacing), pegged.peg.wrapAround!(Spacing, Element, Spacing), pegged.peg.wrapAround!(Spacing, Mustache, Spacing), pegged.peg.wrapAround!(Spacing, HtmlComment, Spacing), pegged.peg.wrapAround!(Spacing, Text, Spacing)), "SvelteKit.MarkupNode")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, IfBlock, Spacing), pegged.peg.wrapAround!(Spacing, EachBlock, Spacing), pegged.peg.wrapAround!(Spacing, Element, Spacing), pegged.peg.wrapAround!(Spacing, Mustache, Spacing), pegged.peg.wrapAround!(Spacing, HtmlComment, Spacing), pegged.peg.wrapAround!(Spacing, Text, Spacing)), "SvelteKit.MarkupNode"), "MarkupNode")(p);
        }
    }
    static TParseTree MarkupNode(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, IfBlock, Spacing), pegged.peg.wrapAround!(Spacing, EachBlock, Spacing), pegged.peg.wrapAround!(Spacing, Element, Spacing), pegged.peg.wrapAround!(Spacing, Mustache, Spacing), pegged.peg.wrapAround!(Spacing, HtmlComment, Spacing), pegged.peg.wrapAround!(Spacing, Text, Spacing)), "SvelteKit.MarkupNode")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, IfBlock, Spacing), pegged.peg.wrapAround!(Spacing, EachBlock, Spacing), pegged.peg.wrapAround!(Spacing, Element, Spacing), pegged.peg.wrapAround!(Spacing, Mustache, Spacing), pegged.peg.wrapAround!(Spacing, HtmlComment, Spacing), pegged.peg.wrapAround!(Spacing, Text, Spacing)), "SvelteKit.MarkupNode"), "MarkupNode")(TParseTree("", false,[], s));
        }
    }
    static string MarkupNode(GetName g)
    {
        return "SvelteKit.MarkupNode";
    }

    static TParseTree MarkupDoc(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, eoi, Spacing)), "SvelteKit.MarkupDoc")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, eoi, Spacing)), "SvelteKit.MarkupDoc"), "MarkupDoc")(p);
        }
    }
    static TParseTree MarkupDoc(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, eoi, Spacing)), "SvelteKit.MarkupDoc")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), pegged.peg.wrapAround!(Spacing, eoi, Spacing)), "SvelteKit.MarkupDoc"), "MarkupDoc")(TParseTree("", false,[], s));
        }
    }
    static string MarkupDoc(GetName g)
    {
        return "SvelteKit.MarkupDoc";
    }

    static TParseTree FilePart(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, ScriptBlock, Spacing), pegged.peg.wrapAround!(Spacing, StyleBlock, Spacing), pegged.peg.wrapAround!(Spacing, HtmlComment, Spacing), pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), "SvelteKit.FilePart")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, ScriptBlock, Spacing), pegged.peg.wrapAround!(Spacing, StyleBlock, Spacing), pegged.peg.wrapAround!(Spacing, HtmlComment, Spacing), pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), "SvelteKit.FilePart"), "FilePart")(p);
        }
    }
    static TParseTree FilePart(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, ScriptBlock, Spacing), pegged.peg.wrapAround!(Spacing, StyleBlock, Spacing), pegged.peg.wrapAround!(Spacing, HtmlComment, Spacing), pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), "SvelteKit.FilePart")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.or!(pegged.peg.wrapAround!(Spacing, ScriptBlock, Spacing), pegged.peg.wrapAround!(Spacing, StyleBlock, Spacing), pegged.peg.wrapAround!(Spacing, HtmlComment, Spacing), pegged.peg.wrapAround!(Spacing, MarkupNode, Spacing)), "SvelteKit.FilePart"), "FilePart")(TParseTree("", false,[], s));
        }
    }
    static string FilePart(GetName g)
    {
        return "SvelteKit.FilePart";
    }

    static TParseTree Document(TParseTree p)
    {
        if(__ctfe)
        {
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, FilePart, Spacing)), pegged.peg.wrapAround!(Spacing, eoi, Spacing)), "SvelteKit.Document")(p);
        }
        else
        {
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, FilePart, Spacing)), pegged.peg.wrapAround!(Spacing, eoi, Spacing)), "SvelteKit.Document"), "Document")(p);
        }
    }
    static TParseTree Document(string s)
    {
        if(__ctfe)
            return         pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, FilePart, Spacing)), pegged.peg.wrapAround!(Spacing, eoi, Spacing)), "SvelteKit.Document")(TParseTree("", false,[], s));
        else
        {
            forgetMemo();
            return hooked!(pegged.peg.defined!(pegged.peg.and!(pegged.peg.wrapAround!(Spacing, Spacing, Spacing), pegged.peg.zeroOrMore!(pegged.peg.wrapAround!(Spacing, FilePart, Spacing)), pegged.peg.wrapAround!(Spacing, eoi, Spacing)), "SvelteKit.Document"), "Document")(TParseTree("", false,[], s));
        }
    }
    static string Document(GetName g)
    {
        return "SvelteKit.Document";
    }

    static TParseTree opCall(TParseTree p)
    {
        TParseTree result = decimateTree(Name(p));
        result.children = [result];
        result.name = "SvelteKit";
        return result;
    }

    static TParseTree opCall(string input)
    {
        forgetMemo();
        return SvelteKit(TParseTree(``, false, [], input, 0, 0));
    }
    static string opCall(GetName g)
    {
        return "SvelteKit";
    }


    static void forgetMemo()
    {
    }
    }
}

alias GenericSvelteKit!(ParseTree).SvelteKit SvelteKit;

